import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:uuid/uuid.dart';
import 'package:zexano_sms/core/utils/normalization_engine.dart';
import 'package:zexano_sms/core/utils/sms_logger.dart';
import 'package:zexano_sms/features/sms/data/datasources/sms_local_source.dart';

/// Listens on the Android EventChannel and processes two event types:
///
/// - `inbound_sms`        : incoming SMS received by [SmsReceiver.kt]
///                          (only fires when the app is in foreground;
///                          background messages are already written to SQLite
///                          directly by [SmsReceiver.kt])
///
/// - `sms_status_update`  : delivery report from [SmsSentReceiver.kt]
///                          Updates the correct row from 'queued' → 'sent'/'failed'.
///
/// Call [init] once in [main.dart] (or after DI is ready) and [dispose] on
/// app shutdown.
class IncomingSmsService {
  static const _eventChannel = EventChannel('com.zexano.sms/incoming');

  final SmsLocalSource _localSource;
  final NormalizationEngine _normalizationEngine;
  final String _defaultTenantId;

  StreamSubscription<dynamic>? _subscription;
  bool _initialized = false; // guard: prevents double init()

  IncomingSmsService({
    required SmsLocalSource localSource,
    required NormalizationEngine normalizationEngine,
    String defaultTenantId = 'default-tenant',
  })  : _localSource = localSource,
        _normalizationEngine = normalizationEngine,
        _defaultTenantId = defaultTenantId;

  /// Starts listening on the Android EventChannel.
  /// Safe to call multiple times — subsequent calls are no-ops.
  void init() {
    if (_initialized) return; // guard
    _initialized = true;
    _subscription = _eventChannel
        .receiveBroadcastStream()
        .listen(_onEvent, onError: _onError);
  }

  final _externalIntentController =
      StreamController<Map<String, dynamic>>.broadcast();

  /// Stream of external SMS intents from Android Phone / Contacts apps.
  Stream<Map<String, dynamic>> get externalSmsIntents =>
      _externalIntentController.stream;

  void dispose() {
    _subscription?.cancel();
    _subscription = null;
    _initialized = false;
    _externalIntentController.close();
  }

  Future<void> _onEvent(dynamic event) async {
    if (event is! Map) return;
    final map = <String, dynamic>{};
    event.forEach((k, v) => map[k.toString()] = v);

    final type = map['type'] as String?;
    switch (type) {
      case 'inbound_sms':
        await _handleInbound(map);
      case 'sms_status_update':
        await _handleStatusUpdate(map);
      case 'external_sms_intent':
        _handleExternalSmsIntent(map);
    }
  }

  void _handleExternalSmsIntent(Map<String, dynamic> map) {
    debugPrint('[IncomingSmsService] received external SMS intent: $map');
    _externalIntentController.add(map);
  }

  Future<void> _handleInbound(Map<String, dynamic> map) async {
    final sender = map['sender'] as String?;
    final body = map['body'] as String?;
    final receivedAt = (map['receivedAt'] as num?)?.toInt();

    // The id was generated by SmsDatabase.kt — it is the single source of truth
    // for the row identity. An empty/absent id means the native write failed;
    // we generate a fallback so the foreground still captures the message.
    final nativeId = map['id'] as String?;

    if (sender == null || body == null || receivedAt == null) return;

    final rowId = (nativeId != null && nativeId.isNotEmpty)
        ? nativeId
        : const Uuid().v4(); // fallback: native write failed

    // تطبيع الرقم قبل البحث في جهات الاتصال:
    // الرقم القادم من SmsReceiver قد يكون بصيغة محلية (مثال: 770542963)
    // بينما الـ DB يخزّنه بالصيغة الدولية (+967770542963).
    final normalizedSender = _normalizationEngine.normalize(sender);

    // Resolve contact name — the one piece of data Dart owns that native lacks.
    final contact = await _localSource.getContactByPhone(normalizedSender);
    final contactName = contact != null
        ? '${contact.firstName} ${contact.lastName}'.trim()
        : null;

    try {
      // Two-phase idempotent write (see SmsLocalSource.insertInboundMessageOrIgnore):
      //
      // Phase 1 — INSERT OR IGNORE with the native PK:
      //   • If native wrote the row already → no-op on this phase.
      //   • If native failed → Flutter writes the row here.
      //
      // Phase 2 — unconditional UPDATE of contact fields:
      //   • Runs even when Phase 1 was a no-op.
      //   • Forces Drift to fire stream notification → UI refreshes from DB.
      //   • DB is always the Source of Truth; the event payload is only used
      //     as a trigger, never as display data.
      //   • Future native fields (SIM slot, URI, PDU…) flow through untouched.
      await _localSource.insertInboundMessageOrIgnore(
        id: rowId,
        tenantId: _defaultTenantId,
        senderPhone: sender,
        body: body,
        receivedAtSeconds: receivedAt,
        contactName: contactName,
        contactId: contact?.id,
      );
    } catch (e) {
      // Non-fatal — native already persisted the row and the user will see it
      // on next screen open via a fresh DB read.
      // ignore: avoid_print
      print('[IncomingSmsService] inbound write error: $e');
    }
  }

  Future<void> _handleStatusUpdate(Map<String, dynamic> map) async {
    final messageId = map['messageId'] as String?;
    final status = map['status'] as String?;

    if (messageId == null || status == null) return;

    // ignore: avoid_print
    print('[SMS STATUS] EVENT RECEIVED messageId=$messageId status=$status');

    // Kotlin (SmsSentReceiver) already wrote the exact status + sentAt
    // directly to SQLite.  We skip a redundant Drift write and just notify
    // the stream system so active .watch() queries re-read the table.
    SmsLogger.statusUpdateNotification(messageId: messageId, status: status);
    _localSource.notifyMessageHistoryUpdated();

    // ignore: avoid_print
    print('[SMS STATUS] DRIFT INVALIDATION messageId=$messageId status=$status');
  }

  void _onError(Object error) {
    // EventChannel errors are non-fatal — log silently.
    // ignore: avoid_print
    print('[IncomingSmsService] EventChannel error: $error');
  }
}
